name: simple
description: Sample Mobile Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+4

environment:
    sdk: '>=2.9.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    flutter_localizations:
        sdk: flutter
    flutter_cupertino_localizations: ^1.0.1

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.3

    # The following adds the shared pref as a dependency in your application
    shared_preferences: ^0.5.10

    #Video Player Plugin
    video_player: ^0.10.12+2
    chewie: ^0.9.10

    # A composable, Future-based library for making HTTP requests.
    http: ^0.12.2
    flutter_html: ^1.0.2
    flutter_widget_from_html: ^0.5.0+3
    flutter_webview_plugin: ^0.3.11

    #to zoom in and out
    photo_view: ^0.10.2

    path_provider: ^1.6.14

    file_picker: ^1.13.3

    # The following adds the launcher icon support to your application.
    # run below mentioned commands to generate launcher icons
    # flutter packages get
    # flutter packages pub run flutter_launcher_icons:main
    flutter_launcher_icons: ^0.7.5

    flutter_native_splash: ^0.1.9

    # Flogs, a powerful logging framework
    f_logs: ^1.2.2

    # MobX is a library for reactively managing the state of your applications. Use the power of
    # observables, actions, and reactions to supercharge your Dart and Flutter apps.
    mobx: ^1.2.1+2
    flutter_mobx: ^1.1.0+2
    mobx_codegen: ^1.1.0+1
    # An helper to easily exposes a value using InheritedWidget without having to write one.
    provider: ^4.0.1

    # String validation and sanitization for Dart. Dart 2-compatible version of validator
    validators: ^2.0.0+1

    # A powerful Http client for Dart
    dio: ^3.0.10

    # A flexible widget for user notification.
    # Do not upgrade until Flutter 1.15 is on stable channel
    flushbar: ^1.10.4

    image_picker: ^0.6.7+7
    flutter_staggered_grid_view: ^0.2.7

    # Material Dialog
    material_dialog: ^0.0.9

    #Date Utility
    date_util: ^0.1.4

    printing: ^3.6.0

    # Dependency injection
    inject:
        git:
            url: https://github.com/dumparun/inject.dart
            path: package/inject

    source_gen: ^0.9.6
    analyzer: ^0.39.14
    intl: ^0.16.1

    url_launcher: ^5.5.3

    form_bloc: ^0.19.1

    flutter_form_bloc: ^0.19.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    json_serializable: ^3.2.5
    build_runner: ^1.10.1
    inject_generator:
        git:
            url: https://github.com/dumparun/inject.dart
            path: package/inject_generator

flutter_icons:
    ios: true
    android: true
    image_path_ios: 'assets/images/launcher/icon.png'
    image_path_android: 'assets/images/launcher/icon.png'
    adaptive_icon_background: '#ffffff'

flutter_native_splash:
    image: assets/images/launcher/splash.png
    color: '#ffffff'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/images/launcher/
        - assets/i18n/


    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.io/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.io/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: ProductSans
          fonts:
              - asset: assets/fonts/Product-Sans-Regular.ttf
              - asset: assets/fonts/Product-Sans-Italic.ttf
                style: italic
              - asset: assets/fonts/Product-Sans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf

        - family: Roboto-medium
          fonts:
              - asset: assets/fonts/Roboto-Medium.ttf
        - family: Roboto-light
          fonts:
              - asset: assets/fonts/Roboto-Light.ttf
    # For details regarding fonts from package dependencies,
    # see https://flutter.io/custom-fonts/#from-packages

    # module:
    #     androidX: true
